# Generated by Django 3.2.4 on 2021-06-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(default='ok'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='ok', max_length=64),
        ),
    ]
